In [56]:
http://web.cs.ucdavis.edu/~filkov/classes/234-S08/secure/clustering.pdf

SyntaxError: invalid syntax (<ipython-input-56-f1fa54cd0501>, line 1)

In [1]:
import pandas as pd
import numpy as np
import datetime as DT
import matplotlib.pyplot as plt
from statsmodels.tools import add_constant
from statsmodels.regression.linear_model import RegressionResults
import seaborn as sns
import sklearn as sk
from sklearn.preprocessing import MinMaxScaler
from sklearn.model_selection import KFold
from sklearn.linear_model import LinearRegression
from sklearn.linear_model import Ridge
from sklearn.linear_model import Lasso
from sklearn.preprocessing import PolynomialFeatures
from sklearn.neighbors import KNeighborsRegressor
from sklearn.decomposition import PCA
from sklearn import tree
import numpy as np
import scipy as sp
import matplotlib.pyplot as plt
import pandas as pd
import seaborn as sns
from sklearn import ensemble
#import pydotplus
#import io
import collections
from sklearn.tree import export_graphviz
from IPython.display import Image
from IPython.display import display
import matplotlib.pyplot as plt
%matplotlib inline
import matplotlib
import matplotlib.pyplot as plt
import matplotlib.cm as cmx
import matplotlib.colors as colors
import matplotlib.patches as patches

to do: 
- Merge

In [2]:
data = pd.read_csv('emporiosirenuse_community_stat.csv',sep=",")

In [3]:
data.head()

,brandname,followers,processedUsers,privateUsers,nopostsUsers,missingUsers,%communityCovered,#communityPosts
0,muzungusisters,66938,22637,34576,3958,8016,88.03,2910277
1,miguelinagambaccini,83848,5634,32186,12930,43561,47.11,670195
2,zeusndione,27624,11384,13540,1694,1899,93.14,1170628
3,dodobaror,89500,31772,40838,6527,13613,84.80,2974526
4,lisamariefernandez,83411,26993,38743,5193,15327,81.63,3230855

In [4]:

data2 = pd.read_csv('emporiosirenuse_domain_stat.csv',sep=",")
data2.head()

,brandname,#posts,%geolocated,#uniquelocations,#like,#tag,#comments,#mentions,#picturetag,#followers
0,miguelinagambaccini,274,60.58,99,139228,1116,921,448,460,82358
1,muzungusisters,262,35.50,48,194003,194,2588,497,79,66950
2,zeusndione,206,20.87,31,131323,1257,883,283,162,27673
3,dodobaror,83,27.71,20,98276,25,1563,556,355,89562
4,lisamariefernandez,335,75.52,96,213419,700,3096,728,553,83421

In [13]:
frames = [data, data2]

result = pd.merge(data, data2, on='brandname', how='outer')

In [16]:
data2

,brandname,#posts,%geolocated,#uniquelocations,#like,#tag,#comments,#mentions,#picturetag,#followers
0,miguelinagambaccini,274,60.58,99,139228,1116,921,448,460,82358
1,muzungusisters,262,35.50,48,194003,194,2588,497,79,66950
2,zeusndione,206,20.87,31,131323,1257,883,283,162,27673
3,dodobaror,83,27.71,20,98276,25,1563,556,355,89562
4,lisamariefernandez,335,75.52,96,213419,700,3096,728,553,83421
5,athenaprocopiou,153,66.01,48,96811,1701,1631,440,377,26593
6,emporiosirenuse,129,82.17,14,20208,3370,557,221,148,3119
7,heidikleinswim,322,51.86,59,62026,5068,1186,377,176,27425
8,loupcharmant,280,20.00,32,55663,434,1629,635,253,20446
9,daftcollectionofficial,89,8.99,7,12868,436,636,144,37,3781

In [54]:
for i in range(10):
    print(df.brandname[i], y_kmeans[i])

muzungusisters 2
miguelinagambaccini 3
zeusndione 1
dodobaror 2
lisamariefernandez 0
athenaprocopiou 1
emporiosirenuse 1
heidikleinswim 1
loupcharmant 1
daftcollectionofficial 1

In [14]:
result

,brandname,followers,processedUsers,privateUsers,nopostsUsers,missingUsers,%communityCovered,#communityPosts,#posts,%geolocated,#uniquelocations,#like,#tag,#comments,#mentions,#picturetag,#followers
0,muzungusisters,66938,22637,34576,3958,8016,88.03,2910277,262,35.50,48,194003,194,2588,497,79,66950
1,miguelinagambaccini,83848,5634,32186,12930,43561,47.11,670195,274,60.58,99,139228,1116,921,448,460,82358
2,zeusndione,27624,11384,13540,1694,1899,93.14,1170628,206,20.87,31,131323,1257,883,283,162,27673
3,dodobaror,89500,31772,40838,6527,13613,84.80,2974526,83,27.71,20,98276,25,1563,556,355,89562
4,lisamariefernandez,83411,26993,38743,5193,15327,81.63,3230855,335,75.52,96,213419,700,3096,728,553,83421
5,athenaprocopiou,26591,10215,12229,1434,3461,86.98,1301625,153,66.01,48,96811,1701,1631,440,377,26593
6,emporiosirenuse,3113,1552,1374,0,201,93.55,223376,129,82.17,14,20208,3370,557,221,148,3119
7,heidikleinswim,27426,8695,15330,0,3408,87.57,983286,322,51.86,59,62026,5068,1186,377,176,27425
8,loupcharmant,20446,12172,4933,705,2922,85.71,1796469,280,20.00,32,55663,434,1629,635,253,20446
9,daftcollectionofficial,3782,2619,595,53,540,85.71,458622,89,8.99,7,12868,436,636,144,37,3781

In [17]:
# normalize so Euclidean isnt affected
# split data into X and y
y = result['brandname']
X = result[result.columns[result.columns != 'brandname']]

# Normalize X's
X = (X - X.mean()) / (X.std())

# rebuild full data set with normalized values
df = pd.DataFrame(y).join(X)

In [18]:
df

,brandname,followers,processedUsers,privateUsers,nopostsUsers,missingUsers,%communityCovered,#communityPosts,#posts,%geolocated,#uniquelocations,#like,#tag,#comments,#mentions,#picturetag,#followers
0,muzungusisters,0.695575,0.896424,0.964586,0.172278,-0.097313,0.347457,1.209832,0.515396,-0.366792,0.081657,1.348538,-0.769640,1.347184,0.350257,-1.064285,0.703748
1,miguelinagambaccini,1.192495,-0.747847,0.812333,2.353593,2.607570,-2.738703,-0.815231,0.642393,0.609659,1.683387,0.542319,-0.195570,-0.659747,0.082510,1.176005,1.159022
2,zeusndione,-0.459715,-0.191795,-0.375499,-0.378156,-0.562801,0.732850,-0.362833,-0.077256,-0.936389,-0.452253,0.425968,-0.107778,-0.705496,-0.819088,-0.576242,-0.456805
3,dodobaror,1.358586,1.779822,1.363503,0.796866,0.328604,0.103852,1.267914,-1.378975,-0.670084,-0.797724,-0.060443,-0.874866,0.113168,0.672646,0.558602,1.371886
4,lisamariefernandez,1.179654,1.317670,1.230042,0.472537,0.459035,-0.135227,1.499639,1.287960,1.191325,1.589167,1.634317,-0.454587,1.958774,1.612494,1.722847,1.190432
5,athenaprocopiou,-0.490071,-0.304842,-0.459015,-0.441369,-0.443937,0.268267,-0.244410,-0.638159,0.821068,0.081657,-0.082005,0.168672,0.195035,0.038796,0.687963,-0.488716
6,emporiosirenuse,-1.180000,-1.142596,-1.150526,-0.790009,-0.692015,0.763772,-1.219161,-0.892153,1.450232,-0.986163,-1.209505,1.207852,-1.097973,-1.157870,-0.658563,-1.182324
7,heidikleinswim,-0.465533,-0.451834,-0.261468,-0.790009,-0.447970,0.312764,-0.532192,1.150380,0.270159,0.427128,-0.593997,2.265088,-0.340709,-0.305450,-0.493922,-0.464133
8,loupcharmant,-0.670649,-0.115591,-0.923802,-0.618607,-0.484954,0.172484,0.202936,0.705891,-0.970261,-0.420847,-0.687652,-0.620208,0.192627,1.104320,-0.041160,-0.670347
9,daftcollectionofficial,-1.160341,-1.039412,-1.200152,-0.777124,-0.666218,0.172484,-1.006495,-1.315476,-1.398918,-1.206008,-1.317541,-0.618963,-1.002863,-1.578615,-1.311246,-1.162763

In [19]:
from sklearn.cluster import KMeans
kmeans = KMeans(n_clusters=4)
kmeans.fit(X)
y_kmeans = kmeans.predict(X)

In [53]:
for i in range(10):
    print(df.brandname[i], y_kmeans[i])

muzungusisters 2
miguelinagambaccini 3
zeusndione 1
dodobaror 2
lisamariefernandez 0
athenaprocopiou 1
emporiosirenuse 1
heidikleinswim 1
loupcharmant 1
daftcollectionofficial 1

In [55]:
from sklearn.cluster import KMeans
kmeans = KMeans(n_clusters=3)
kmeans.fit(X)
y_kmeans = kmeans.predict(X)

for i in range(10):
    print(df.brandname[i], y_kmeans[i])

muzungusisters 1
miguelinagambaccini 2
zeusndione 0
dodobaror 1
lisamariefernandez 1
athenaprocopiou 0
emporiosirenuse 0
heidikleinswim 0
loupcharmant 0
daftcollectionofficial 0

Things to ask WP Monday @ 10AM: 

about the cluster: 
- We don't have data on the actual followers (i.e. ndeosrnenney. All we see if that he/she follows one of the brands...not how many followers, posts, etc).
Instead- I clustered the diff companies on multi-D planes, and limited k means to 3 and 4: 
- how to tell what its picking up on?
- I could do PCA then cluster- but it seems MORE diff to interpret